parameters:
    tchoulom.viewcounter.command.base.class: Tchoulom\ViewCounterBundle\Command\AbstractCommand
    tchoulom.viewcounter_cleanup.command.class: Tchoulom\ViewCounterBundle\Command\ViewcounterCleanupCommand

services:

    # Abstract Command
    tchoulom.viewcounter.command.base:
        class: '%tchoulom.viewcounter.command.base.class%'
        abstract:  true
        public: true
        arguments:
            - '@tchoulom.viewcounter.manager'

    # CleanupViewcounterCommand
    tchoulom.viewcounter_cleanup.command:
        class: '%tchoulom.viewcounter_cleanup.command.class%'
        parent: tchoulom.viewcounter.command.base
        public: true
        tags:
            - { name: console.command }

    # aliases needed for services (Symfony version 4, 5)
    Tchoulom\ViewCounterBundle\Command\AbstractCommand: '@tchoulom.viewcounter.command.base'
    Tchoulom\ViewCounterBundle\Command\ViewcounterCleanupCommand: '@tchoulom.viewcounter_cleanup.command'
