parameters:
    tchoulom.viewcounter.filemanager.class: Tchoulom\ViewCounterBundle\Manager\FileManager

services:
    # FileManager
    tchoulom.viewcounter.filemanager:
        class: '%tchoulom.viewcounter.filemanager.class%'
        public: true
        arguments:
            - '%kernel.project_dir%'
            - '@tchoulom.viewcounter_config'

    # aliases needed for services (Symfony version 4, 5)
    Tchoulom\ViewCounterBundle\Manager\FileManager: '@tchoulom.viewcounter.filemanager'
