parameters:
    tchoulom.view_counter.base.class: Tchoulom\ViewCounterBundle\Counter\AbstractViewCounter
    tchoulom.view_counter.class: Tchoulom\ViewCounterBundle\Counter\ViewCounter
    tchoulom.view_counter.repository.base.class: Tchoulom\ViewCounterBundle\Repository\AbstractRepository
    tchoulom.view_counter.repository.class: Tchoulom\ViewCounterBundle\Repository\CounterRepository
    tchoulom.view_counter.manager.class: Tchoulom\ViewCounterBundle\Manager\CounterManager

services:
    # Counter
    tchoulom.view_counter.base:
        class: '%tchoulom.view_counter.base.class%'
        abstract:  true
        public: true
        arguments:
            - '@tchoulom.view_counter.manager'
            - '@request_stack'
            - '%view_interval%'

    tchoulom.view_counter:
        class: '%tchoulom.view_counter.class%'
        public: true
        parent: tchoulom.view_counter.base

    # Repository
    tchoulom.view_counter.repository.base:
        class: '%tchoulom.view_counter.repository.base.class%'
        abstract:  true
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'

    tchoulom.view_counter.repository:
        class: '%tchoulom.view_counter.repository.class%'
        public: true
        parent: tchoulom.view_counter.repository.base

    # Manager
    tchoulom.view_counter.manager:
        class: '%tchoulom.view_counter.manager.class%'
        public: true
        arguments:
            - '@tchoulom.view_counter.repository'