parameters:
    tchoulom.view_counter.class: Tchoulom\ViewCounterBundle\Service\ViewCounter

services:
    tchoulom.view_counter:
        class: "%tchoulom.view_counter.class%"
        arguments: ['@doctrine.orm.entity_manager', '@request_stack']