parameters:
    tchoulom.viewcounter.statistics.class: Tchoulom\ViewCounterBundle\Statistics\Statistics
    tchoulom.viewcounter.stats_builder.class: Tchoulom\ViewCounterBundle\Statistics\StatsBuilder
    tchoulom.viewcounter.stats_finder.class: Tchoulom\ViewCounterBundle\Finder\StatsFinder
    tchoulom.viewcounter.stats_computer.class: Tchoulom\ViewCounterBundle\Compute\StatsComputer

services:
    # Statistics
    tchoulom.viewcounter.statistics:
        class: '%tchoulom.viewcounter.statistics.class%'
        public: true
        arguments:
            - '@tchoulom.viewcounter.filesystem'
            - '@tchoulom.viewcounter.stats_builder'

    # StatsBuilder
    tchoulom.viewcounter.stats_builder:
        class: '%tchoulom.viewcounter.stats_builder.class%'
        public: true
        arguments: ['@tchoulom.viewcounter.geolocator_adapter']

    # StatsFinder
    tchoulom.viewcounter.stats_finder:
        class: '%tchoulom.viewcounter.stats_finder.class%'
        public: true
        arguments: ['@tchoulom.viewcounter.filesystem']

    # StatsComputer
    tchoulom.viewcounter.stats_computer:
        class: '%tchoulom.viewcounter.stats_computer.class%'
        public: true

    # aliases needed for services (Symfony version 4, 5)
    Tchoulom\ViewCounterBundle\Statistics\Statistics: '@tchoulom.viewcounter.statistics'
    Tchoulom\ViewCounterBundle\Statistics\StatsBuilder: '@tchoulom.viewcounter.stats_builder'
    Tchoulom\ViewCounterBundle\Finder\StatsFinder: '@tchoulom.viewcounter.stats_finder'
    Tchoulom\ViewCounterBundle\Compute\StatsComputer: '@tchoulom.viewcounter.stats_computer'
