parameters:
    tchoulom.viewcounter.statistics.class: Tchoulom\ViewCounterBundle\Statistics\Statistics
    tchoulom.viewcounter.stats_finder.class: Tchoulom\ViewCounterBundle\Finder\StatsFinder
    tchoulom.viewcounter.filesystem.class: Tchoulom\ViewCounterBundle\Filesystem\Filesystem

services:
    # Statistics
    tchoulom.viewcounter.statistics:
        class: '%tchoulom.viewcounter.statistics.class%'
        public: true
        arguments: ['@tchoulom.viewcounter.filesystem']

    # StatsFinder
    tchoulom.viewcounter.stats_finder:
        class: '%tchoulom.viewcounter.stats_finder.class%'
        public: true
        arguments: ['@tchoulom.viewcounter.filesystem']

    # Filesystem
    tchoulom.viewcounter.filesystem:
        class: '%tchoulom.viewcounter.filesystem.class%'
        public: true
        arguments:
            - '%kernel.project_dir%'
            - '@tchoulom.viewcounter_config'
